services:
  botarena-app:
    build: .
    container_name: botarena_prod
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - SENTRY_DSN=${SENTRY_DSN}
      - CHOKIDAR_USEPOLLING=true
